#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint-staged..."
npx lint-staged

if [ $? -ne 0 ]; then
  echo "Lint-staged failed. Aborting commit."
  exit 1
fi

echo "Running build..."
npm run build

if [ $? -ne 0 ]; then
  echo "Build failed. Aborting commit."
  exit 1
fi

echo "Pre-commit hook completed successfully."
echo "Commit successful!"